# .github/workflows/build-apk.yml

name: Build APK (Alpine Linux)

on:
  push:
    branches: [ master ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: alpine:latest

    steps:
      - name: Install build tools
        run: |
          apk update
          apk add alpine-sdk cmake git libdrm-dev pkgconf curl

      - name: Set up user for abuild
        run: |
            adduser -D builder
            addgroup builder abuild
            echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
            mkdir -p /home/builder/packages/ttyimg
            chown -R builder /home/builder
            chown -R builder /var/cache/distfiles
  

      - name: Checkout source
        uses: actions/checkout@v4
        with:
          path: ttyimg-src

      - name: Create tarball and APKBUILD
        run: |
          cd ttyimg-src
          tar -czf ttyimg-1.0.tar.gz --transform 's,^,ttyimg-1.0/,' *
          mv ttyimg-1.0.tar.gz /home/builder/packages/ttyimg/
          cp APKBUILD /home/builder/packages/ttyimg/
          chown builder /home/builder/packages/ttyimg/*

      - name: Build APK
        run: |
          su builder -c "abuild-keygen -a -n"
          BUILDER_KEY=$(find /home/builder/.abuild -name '*.rsa' | head -n 1)
          echo "PACKAGER_PRIVKEY=\"$BUILDER_KEY\"" >> /home/builder/.abuild/abuild.conf
          su builder -c "cd /home/builder/packages/ttyimg && abuild checksum && abuild -r"

      - name: Upload built APK
        uses: actions/upload-artifact@v4
        with:
          name: ttyimg-apk
          path: /home/builder/packages/ttyimg/packages/**/*.apk
