name: Build APK (Alpine Linux)

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: alpine:latest

    steps:
      - name: Install build tools
        run: |
          apk update
          apk add alpine-sdk sudo cmake git libdrm-dev pkgconf

      - name: Create builder user
        run: |
          adduser -D builder
          echo "builder ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers
          mkdir -p /home/builder/packages/ttyimg
          chown -R builder /home/builder

      - name: Checkout source
        uses: actions/checkout@v4

      - name: Copy project into user home
        run: |
          cp -r . /home/builder/packages/ttyimg/
          chown -R builder /home/builder/packages/ttyimg

      - name: Build APK as user
        run: |
          sudo -u builder -H sh -c '
            cd /home/builder/packages/ttyimg
            abuild-keygen -a -n
            abuild checksum
            abuild -r
          '

      - name: Upload built .apk
        uses: actions/upload-artifact@v4
        with:
          name: ttyimg-apk
          path: /home/builder/packages/ttyimg/packages/**/*.apk
